Name=zero-lliurex-s4a
Name[es]=Instalador del Scratch for Arduino
Name[qcv]=Instal·lador del Scratch for Arduino
Name[ca_ES]=Instal·lador del Scratch for Arduino
Comment=Scratch for Arduino
Comment[es]=Instalador del Scratch for Arduino
Comment[qcv]=Instal·lador del Scratch for Arduino
Comment[ca_ES]=Instal·lador del Scratch for Arduino
Icon=s4a
Category=Software
ScriptPath=zero-lliurex-s4a.zmd
Groups=adm;admins;teachers
Using=pe
Service=True
Modal=True
Gnome-terminal=True 
